# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudgov < Formula
  desc "AWS governance CLI — IAM least-privilege, cost anomalies, posture, drift, compliance, and resource hygiene across AWS, plus a Kubernetes RBAC scanner"
  homepage "https://github.com/nanohype/cloudgov"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nanohype/cloudgov/releases/download/v2.0.0/cloudgov_2.0.0_darwin_amd64.tar.gz"
      sha256 "9906388a3f4d6b70584c3fc9172088dd312783264925f3e8665003c827910fc8"

      define_method(:install) do
        bin.install "cloudgov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nanohype/cloudgov/releases/download/v2.0.0/cloudgov_2.0.0_darwin_arm64.tar.gz"
      sha256 "8c54cf43aead2681762f24c03cd041c44e73cbc66b7ae4e6176064b929a212b4"

      define_method(:install) do
        bin.install "cloudgov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanohype/cloudgov/releases/download/v2.0.0/cloudgov_2.0.0_linux_amd64.tar.gz"
      sha256 "4dd270c232b61a9696e3d6f0dbe9e5c353602eca7997fa51fc33f248f3365f61"
      define_method(:install) do
        bin.install "cloudgov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nanohype/cloudgov/releases/download/v2.0.0/cloudgov_2.0.0_linux_arm64.tar.gz"
      sha256 "beb1e1007a3900794c741352a49e6fd8658e7fa04fe1d8257dc80db699fcdaa1"
      define_method(:install) do
        bin.install "cloudgov"
      end
    end
  end

  test do
    system "#{bin}/cloudgov", "--version"
  end
end
